Persian(fa) Package
solidjs/solid-docs-legacy pull request #251
Opened 2023-04-06 02:12 UTC by Ehsan-Home

Hi.

In this pull request, I have added the Persian(fa) package to solid docs.

I have translated some parts of the `comparison.md` file and the translation of the rest is ongoing.

Please let me know if any files need to be changed.
Thanks 👋🏻

2023-04-08 09:35 UTC, aminya requested changes
Looks great. I left some suggestions. Thanks for initiating this! 💯

2023-04-08 09:35 UTC, aminya commented on langs/fa/guides/comparison.md
> +## ری اکت (React)
Could you use semi-space in the React name? (نیم فاصله)
```suggestion
## ری‌اکت (React)
```

2023-04-08 09:35 UTC, aminya commented on langs/fa/guides/comparison.md
> +ری اکت (React) تأثیر زیادی روی Solid داشته است. سالید ایده (Solid) جریان یک طرفه ارسال داده ها و تفکیک صریح خواندن و نوشتن در Hooks ها را از React الهام گرفته است. Solid ایده ها و نظرات قوی و جذابی د
Could you replace the remaining English words and names with their translation? Here I replaced some of them as an example. 

```suggestion
ری‌اکت (React) تأثیر زیادی روی سالید (Solid) داشته است. سالید ایده جریان یک طرفه ارسال داده ها و تفکیک صریح خواندن و نوشتن در هوک ها (Hooks) را از ری‌اکت الهام گرفته است. سالید ایده ها و نظرات قوی و جذابی در مورد چگونگی رویکرد مدیریت داده در توسعه برنامه دارد، اما به دنبال محدود کردن اجرای آن نیست.

```

2023-04-18 01:57 UTC, Ehsan-Home commented on langs/fa/guides/comparison.md
> +ری اکت (React) تأثیر زیادی روی Solid داشته است. سالید ایده (Solid) جریان یک طرفه ارسال داده ها و تفکیک صریح خواندن و نوشتن در Hooks ها را از React الهام گرفته است. Solid ایده ها و نظرات قوی و جذابی د
Hi Amin.

Thanks for the suggestions!

I added the Persian equivalents and technical english names in parentheses.

2023-04-18 04:14 UTC, aminya approved these changes

2023-10-09 14:47 UTC, merged